import type { Deck } from "../types";

const now = Date.now();

export const SAMPLE_DECKS: Deck[] = [
	{
		id: "deck-1",
		name: "Spanish Vocabulary",
		description: "Essential words and phrases for everyday conversation",
		cards: [
			{
				id: "card-1-1",
				deckId: "deck-1",
				front: "House",
				back: "Casa",
				interval: 1,
				easeFactor: 2.5,
				nextReview: now,
			},
			{
				id: "card-1-2",
				deckId: "deck-1",
				front: "Car",
				back: "Coche",
				interval: 1,
				easeFactor: 2.5,
				nextReview: now,
			},
			{
				id: "card-1-3",
				deckId: "deck-1",
				front: "Book",
				back: "Libro",
				interval: 1,
				easeFactor: 2.5,
				nextReview: now,
			},
			{
				id: "card-1-4",
				deckId: "deck-1",
				front: "Water",
				back: "Agua",
				interval: 1,
				easeFactor: 2.5,
				nextReview: now,
			},
			{
				id: "card-1-5",
				deckId: "deck-1",
				front: "To Eat",
				back: "Comer",
				interval: 1,
				easeFactor: 2.5,
				nextReview: now,
			},
			{
				id: "card-1-6",
				deckId: "deck-1",
				front: "Hello",
				back: "Hola",
				interval: 1,
				easeFactor: 2.5,
				nextReview: now,
			},
			{
				id: "card-1-7",
				deckId: "deck-1",
				front: "Thank you",
				back: "Gracias",
				interval: 1,
				easeFactor: 2.5,
				nextReview: now,
			},
			{
				id: "card-1-8",
				deckId: "deck-1",
				front: "Please",
				back: "Por favor",
				interval: 1,
				easeFactor: 2.5,
				nextReview: now,
			},
			{
				id: "card-1-9",
				deckId: "deck-1",
				front: "Good morning",
				back: "Buenos días",
				interval: 1,
				easeFactor: 2.5,
				nextReview: now,
			},
			{
				id: "card-1-10",
				deckId: "deck-1",
				front: "Where is the bathroom?",
				back: "¿Dónde está el baño?",
				interval: 1,
				easeFactor: 2.5,
				nextReview: now,
			},
		],
	},
	{
		id: "deck-2",
		name: "JavaScript Concepts",
		description: "Core programming concepts and syntax",
		cards: [
			{
				id: "card-2-1",
				deckId: "deck-2",
				front: "What is a closure?",
				back: "A function that remembers the environment in which it was created.",
				interval: 1,
				easeFactor: 2.5,
				nextReview: now,
			},
			{
				id: "card-2-2",
				deckId: "deck-2",
				front: "Explain 'this' keyword in JavaScript.",
				back: "Refers to the context in which a function is executed. Can be the global object, an object instance, or null in strict mode.",
				interval: 1,
				easeFactor: 2.5,
				nextReview: now,
			},
			{
				id: "card-2-3",
				deckId: "deck-2",
				front: "What is the difference between '==' and '==='?",
				back: "'==' performs type coercion before comparison, while '===' checks for both value and type equality.",
				interval: 1,
				easeFactor: 2.5,
				nextReview: now,
			},
			{
				id: "card-2-4",
				deckId: "deck-2",
				front: "What are arrow functions?",
				back: "A concise way to write function expressions, with a shorter syntax and lexical 'this' binding.",
				interval: 1,
				easeFactor: 2.5,
				nextReview: now,
			},
			{
				id: "card-2-5",
				deckId: "deck-2",
				front: "What is `async/await`?",
				back: "Syntactic sugar for working with Promises, making asynchronous code look and behave more like synchronous code.",
				interval: 1,
				easeFactor: 2.5,
				nextReview: now,
			},
			{
				id: "card-2-6",
				deckId: "deck-2",
				front: "What is event bubbling?",
				back: "The process where an event triggered on an element first triggers the event handler on that element, then on its parent, and so on, up the DOM tree.",
				interval: 1,
				easeFactor: 2.5,
				nextReview: now,
			},
			{
				id: "card-2-7",
				deckId: "deck-2",
				front: "Explain `map`, `filter`, and `reduce`.",
				back: "`map`: creates a new array by applying a function to each element.\n`filter`: creates a new array with elements that pass a test.\n`reduce`: applies a function against an accumulator and each element to reduce it to a single value.",
				interval: 1,
				easeFactor: 2.5,
				nextReview: now,
			},
			{
				id: "card-2-8",
				deckId: "deck-2",
				front: "What is the DOM?",
				back: "Document Object Model. A tree-like structure representing the HTML document, allowing JavaScript to interact with the page's content and structure.",
				interval: 1,
				easeFactor: 2.5,
				nextReview: now,
			},
			{
				id: "card-2-9",
				deckId: "deck-2",
				front: "What is a Promise?",
				back: "An object that represents the eventual completion (or failure) of an asynchronous operation, and its resulting value.",
				interval: 1,
				easeFactor: 2.5,
				nextReview: now,
			},
			{
				id: "card-2-10",
				deckId: "deck-2",
				front: "What is hoisting?",
				back: "JavaScript's behavior of moving declarations of functions and variables to the top of their containing scope before code execution.",
				interval: 1,
				easeFactor: 2.5,
				nextReview: now,
			},
		],
	},
	{
		id: "deck-3",
		name: "Art History",
		description: "Famous artists, movements, and masterpieces",
		cards: [
			{
				id: "card-3-1",
				deckId: "deck-3",
				front: "Who painted the Mona Lisa?",
				back: "Leonardo da Vinci",
				interval: 1,
				easeFactor: 2.5,
				nextReview: now,
			},
			{
				id: "card-3-2",
				deckId: "deck-3",
				front: "What is Impressionism?",
				back: "An art movement characterized by its emphasis on capturing the fleeting impression of a moment, often with visible brushstrokes and focus on light.",
				interval: 1,
				easeFactor: 2.5,
				nextReview: now,
			},
			{
				id: "card-3-3",
				deckId: "deck-3",
				front: "Name a famous Surrealist artist.",
				back: "Salvador Dalí",
				interval: 1,
				easeFactor: 2.5,
				nextReview: now,
			},
			{
				id: "card-3-4",
				deckId: "deck-3",
				front: "What is 'The Starry Night'?",
				back: "A famous oil painting by Vincent van Gogh, depicting the view from his asylum room.",
				interval: 1,
				easeFactor: 2.5,
				nextReview: now,
			},
			{
				id: "card-3-5",
				deckId: "deck-3",
				front: "Who is considered the father of Cubism?",
				back: "Pablo Picasso",
				interval: 1,
				easeFactor: 2.5,
				nextReview: now,
			},
			{
				id: "card-3-6",
				deckId: "deck-3",
				front: "What era is Michelangelo associated with?",
				back: "The High Renaissance",
				interval: 1,
				easeFactor: 2.5,
				nextReview: now,
			},
			{
				id: "card-3-7",
				deckId: "deck-3",
				front: "What is the Sistine Chapel ceiling famously painted by?",
				back: "Michelangelo",
				interval: 1,
				easeFactor: 2.5,
				nextReview: now,
			},
			{
				id: "card-3-8",
				deckId: "deck-3",
				front:
					"Which movement is famous for works like 'The Persistence of Memory'?",
				back: "Surrealism",
				interval: 1,
				easeFactor: 2.5,
				nextReview: now,
			},
			{
				id: "card-3-9",
				deckId: "deck-3",
				front: "What is a Renaissance?",
				back: "A period of European cultural, artistic, political, and economic rebirth following the Middle Ages.",
				interval: 1,
				easeFactor: 2.5,
				nextReview: now,
			},
			{
				id: "card-3-10",
				deckId: "deck-3",
				front: "Name a key characteristic of Baroque art.",
				back: "Dramatic intensity, grandeur, rich colors, and strong contrasts.",
				interval: 1,
				easeFactor: 2.5,
				nextReview: now,
			},
		],
	},
	{
		id: "deck-4",
		name: "World Capitals",
		description: "Capitals of countries around the globe",
		cards: [
			{
				id: "card-4-1",
				deckId: "deck-4",
				front: "France",
				back: "Paris",
				interval: 1,
				easeFactor: 2.5,
				nextReview: now,
			},
			{
				id: "card-4-2",
				deckId: "deck-4",
				front: "Japan",
				back: "Tokyo",
				interval: 1,
				easeFactor: 2.5,
				nextReview: now,
			},
			{
				id: "card-4-3",
				deckId: "deck-4",
				front: "Canada",
				back: "Ottawa",
				interval: 1,
				easeFactor: 2.5,
				nextReview: now,
			},
			{
				id: "card-4-4",
				deckId: "deck-4",
				front: "Australia",
				back: "Canberra",
				interval: 1,
				easeFactor: 2.5,
				nextReview: now,
			},
			{
				id: "card-4-5",
				deckId: "deck-4",
				front: "Brazil",
				back: "Brasília",
				interval: 1,
				easeFactor: 2.5,
				nextReview: now,
			},
			{
				id: "card-4-6",
				deckId: "deck-4",
				front: "India",
				back: "New Delhi",
				interval: 1,
				easeFactor: 2.5,
				nextReview: now,
			},
			{
				id: "card-4-7",
				deckId: "deck-4",
				front: "Germany",
				back: "Berlin",
				interval: 1,
				easeFactor: 2.5,
				nextReview: now,
			},
		],
	},
];
